title: wazabike
description: Break The Rules
author: wazabike
logo: /wazabike.github.io/static/img/logo.png
github: https://github.com/wazabike
about: Xe ôm đêêiiiii

baseurl: ""
url: "https://wazabike.github.io"

allowsearch: true

disqus_shortname: longvox
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
